

var codePage =
[
  {number:58 , escaped: "\'20", unescaped: "&nbsp;",name: " Space"},
{number:58 , escaped: "\'21", unescaped: "!",name: " Exclamation mark "},
{number:34 , escaped: "\'22" , unescaped: "\"",name: "Double quote "},
{number:58 , escaped: "\'23", unescaped: "#",name: " Number "},
{number:36 , escaped: "\'24" , unescaped: "$",name: "Dollar "},
{number:58 , escaped: "\'25", unescaped: "%",name: " Percent "},
{number:58 , escaped: "\'26", unescaped: "&amp;",name: " Ampersand "},
{number:39 , escaped: "\'27" , unescaped: "'",name: "Apostrophe "},
{number:58 , escaped: "\'28", unescaped: "(",name: " Left parenthesis "},
{number:58 , escaped: "\'29", unescaped: ")",name: " Right parenthesis "},
{number:42 , escaped: "\'2a" , unescaped: "*",name: "Asterisk "},
{number:58 , escaped: "\'2b", unescaped: "+",name: " Plus sign "},
{number:44 , escaped: "\'2c" , unescaped:",",name: "Comma "},
{number:58 , escaped: "\'2d", unescaped: "-",name: " Hyphen"},
{number:46 , escaped: "\'2e" , unescaped: ".",name: " , Period" },
{number:47 , escaped: "\'2f" , unescaped: "/",name: "Slash" },

{number:48 , escaped: "\'30" , unescaped: "0",name: ""},
{number:49 , escaped: "\'31" , unescaped: "1",name: ""},
{number:50 , escaped: "\'32" , unescaped: "2",name: ""},
{number:51 , escaped: "\'33" , unescaped: "3",name: ""},
{number:52 , escaped: "\'34" , unescaped: "4",name: ""},
{number:53 , escaped: "\'35" , unescaped: "5",name: ""},
{number:54 , escaped: "\'36" , unescaped: "6",name: ""},
{number:55 , escaped: "\'37" , unescaped: "7",name: ""},
{number:56 , escaped: "\'38" , unescaped: "8",name: ""},
{number:57 , escaped: "\'39" , unescaped: "9",name: ""},

{number:58 , escaped: "\'3a", unescaped: ":",name: " Colon "},
{number:58 , escaped: "\'3b", unescaped: ";",name: " Semicolon "},
{number:58 , escaped: "\'3c", unescaped: "&lt;",name: " Less-than sign "},
{number:58 , escaped: "\'3d", unescaped: "=",name: " Equals sign "},
{number:58 , escaped: "\'3e", unescaped: "&gt;",name: " Greater-than sign "},
{number:58 , escaped: "\'3f", unescaped: "?",name: " Question mark "},
{number:58 , escaped: "\'40", unescaped: "@",name: " Commercial at sign "},
{number:58 , escaped: "\'41", unescaped: "A",name: ""},
{number:58 , escaped: "\'42", unescaped: "B",name: " "},
{number:58 , escaped: "\'43", unescaped: "C",name: " "},
{number:58 , escaped: "\'44", unescaped: "D",name: " "},
{number:58 , escaped: "\'45", unescaped: "E",name: " "},
{number:58 , escaped: "\'46", unescaped: "F",name: " "},
{number:58 , escaped: "\'47", unescaped: "G",name: " "},
{number:58 , escaped: "\'48", unescaped: "H",name: " "},
{number:58 , escaped: "\'49", unescaped: "I",name: " "},
{number:58 , escaped: "\'4a", unescaped: "J",name: " "},
{number:58 , escaped: "\'4b", unescaped: "K",name: " "},
{number:58 , escaped: "\'4c", unescaped: "L",name: " "},
{number:58 , escaped: "\'4d", unescaped: "M",name: " "},
{number:58 , escaped: "\'4e", unescaped: "N",name: " "},
{number:58 , escaped: "\'4f", unescaped: "O",name: " "},
{number:58 , escaped: "\'50", unescaped: "P",name: " "},
{number:58 , escaped: "\'51", unescaped: "Q",name: " "},
{number:58 , escaped: "\'52", unescaped: "R",name: " "},
{number:58 , escaped: "\'53", unescaped: "S",name: " "},
{number:58 , escaped: "\'54", unescaped: "T",name: " "},
{number:58 , escaped: "\'55", unescaped: "U",name: " "},
{number:58 , escaped: "\'56", unescaped: "V",name: " "},
{number:58 , escaped: "\'57", unescaped: "W",name: " "},
{number:58 , escaped: "\'58", unescaped: "X",name: " "},
{number:58 , escaped: "\'59", unescaped: "Y",name: " "},
{number:58 , escaped: "\'5a", unescaped: "Z",name: " "},
{number:58 , escaped: "\'5b", unescaped: "[",name: " Left square bracket 92 , \'5c , \ , Backslash "},
{number:58 , escaped: "\'5d", unescaped: "]",name: " Right square bracket "},
{number:58 , escaped: "\'5e", unescaped: "^",name: " Caret "},
{number:58 , escaped: "\'5f", unescaped: "_",name: " Underscore "},
{number:58 , escaped: "\'60", unescaped: "`",name: " Grave accent "},
{number:58 , escaped: "\'61", unescaped: "a",name: " "},
{number:58 , escaped: "\'62", unescaped: "b",name: " "},
{number:58 , escaped: "\'63", unescaped: "c",name: " "},
{number:58 , escaped: "\'64", unescaped: "d",name: " "},
{number:58 , escaped: "\'65", unescaped: "e",name: " "},
{number:58 , escaped: "\'66", unescaped: "f",name: " "},
{number:58 , escaped: "\'67", unescaped: "g",name: " "},
{number:58 , escaped: "\'68", unescaped: "h",name: " "},
{number:58 , escaped: "\'69", unescaped: "i",name: " "},
{number:58 , escaped: "\'6a", unescaped: "j",name: " "},
{number:58 , escaped: "\'6b", unescaped: "k",name: " "},
{number:58 , escaped: "\'6c", unescaped: "l",name: " "},
{number:58 , escaped: "\'6d", unescaped: "m",name: " "},
{number:58 , escaped: "\'6e", unescaped: "n",name: " "},
{number:58 , escaped: "\'6f", unescaped: "o",name: " "},
{number:58 , escaped: "\'70", unescaped: "p",name: " "},
{number:58 , escaped: "\'71", unescaped: "q",name: " "},
{number:58 , escaped: "\'72", unescaped: "r",name: " "},
{number:58 , escaped: "\'73", unescaped: "s",name: " "},
{number:58 , escaped: "\'74", unescaped: "t",name: " "},
{number:58 , escaped: "\'75", unescaped: "u",name: " "},
{number:58 , escaped: "\'76", unescaped: "v",name: " "},
{number:58 , escaped: "\'77", unescaped: "w",name: " "},
{number:58 , escaped: "\'78", unescaped: "x",name: " "},
{number:58 , escaped: "\'79", unescaped: "y",name: " "},
{number:58 , escaped: "\'7a", unescaped: "z",name: " "},
{number:58 , escaped: "\'7c", unescaped: "|",name: " Vertical bar "},
{number:58 , escaped: "\'7d", unescaped: "}",name: " Right curly brace "},
{number:58 , escaped: "\'7e", unescaped: "~",name: " Tilde "},
{number:58 , escaped: "\'80", unescaped: "€",name: ""},
{number:58 , escaped: "\'83", unescaped: "ƒ",name: " Florin "},
{number:58 , escaped: "\'84", unescaped: "",name:", , Low left double quote "},
{number:58 , escaped: "\'85", unescaped: "...",name: " Ellipsis "},
{number:58 , escaped: "\'86", unescaped: "†",name: " Dagger "},
{number:58 , escaped: "\'87", unescaped: "‡",name: " Double dagger "},
{number:58 , escaped: "\'88", unescaped: "∘",name: " Circumflex "},
{number:58 , escaped: "\'89", unescaped: "‰",name: " Permil "},
{number:58 , escaped: "\'8a", unescaped: "Š",name: " S-caron "},
{number:58 , escaped: "\'8b", unescaped: "‹",name: " Single left guillemet "},
{number:58 , escaped: "\'8c", unescaped: "Œ",name: " OE-ligature "},
{number:58 , escaped: "\'8e", unescaped: "Ž",name: " Z-caron "},
{number:58 , escaped: "\'91", unescaped: "‘",name: " Left single quote "},
{number:58 , escaped: "\'92", unescaped: "’",name: " Right single quote "},
{number:58 , escaped: "\'93", unescaped: "“",name: " Left double quote "},
{number:58 , escaped: "\'94", unescaped: "”",name: " Right double quote "},
{number:58 , escaped: "\'95", unescaped: "•",name: " Bullet "},
{number:58 , escaped: "\'96", unescaped: "–",name: " En dash "},
{number:58 , escaped: "\'97", unescaped: "—",name: " Em dash "},
{number:58 , escaped: "\'98", unescaped: "~",name: " Tilde "},
{number:58 , escaped: "\'99", unescaped: "™",name: " Trademark "},
{number:58 , escaped: "\'9a", unescaped: "š",name: " s-caron "},
{number:58 , escaped: "\'9b", unescaped: "›",name: " Single right guillemet "},
{number:58 , escaped: "\'9c", unescaped: "œ",name: " oe ligature "},
{number:58 , escaped: "\'9e", unescaped: "ž",name: " z-caron "},
{number:58 , escaped: "\'9f", unescaped: "Ÿ",name: " Y-diaeresis "},
{number:58 , escaped: "\~", unescaped: "&nbsp;",name: " Nonbreaking space"},
{number:58 , escaped: "\'a1", unescaped: "¡",name: " Inverted exclamation point "},
{number:58 , escaped: "\'a2", unescaped: "¢",name: " Cent sign "},
{number:58 , escaped: "\'a3", unescaped: "£",name: " Pound sign "},
{number:58 , escaped: "\'a4", unescaped: "¤",name: " General currency sign "},
{number:58 , escaped: "\'a5", unescaped: "¥",name: " Yen sign "},
{number:58 , escaped: "\'a6", unescaped: "¦",name: " Broken vertical bar "},
{number:58 , escaped: "\'a7", unescaped: "§",name: " Section sign "},
{number:58 , escaped: "\'a8", unescaped: "¨",name: " Spacing diaeresis "},
{number:58 , escaped: "\'a9", unescaped: "©",name: " Copyright "},
{number:58 , escaped: "\'aa", unescaped: "ª",name: " Feminine ordinal "},
{number:58 , escaped: "\'ab", unescaped: "«",name: " Left angle quotes "},
{number:58 , escaped: "\'ac", unescaped: "¬",name: " Not sign "},
{number:58 , escaped: "\-", unescaped: "(-)",name: " Soft hyphen"},
{number:58 , escaped: "\'ae", unescaped: "®",name: " Registered trademark"},
{number:58 , escaped: "\'af", unescaped: "¯",name: " Macron accent "},
{number:58 , escaped: "\'b0", unescaped: "°",name: " Degree sign "},
{number:58 , escaped: "\'b1", unescaped: "±",name: " Plus or minus sign "},
{number:58 , escaped: "\'b2", unescaped: "²",name: " Superscript 2 "},
{number:58 , escaped: "\'b3", unescaped: "³",name: " Superscript 3 "},
{number:58 , escaped: "\'b4", unescaped: "´",name: " Acute accent "},
{number:58 , escaped: "\'b5", unescaped: "µ",name: " Micro sign (Greek mu) "},
{number:58 , escaped: "\'b6", unescaped: "¶",name: " Paragraph sign "},
{number:58 , escaped: "\'b7", unescaped: "·",name: " Middle dot "},
{number:58 , escaped: "\'b8", unescaped: "¸",name: " Cedilla "},
{number:58 , escaped: "\'b9", unescaped: "¹",name: " Superscript 1 "},
{number:58 , escaped: "\'ba", unescaped: "º",name: " Masculine ordinal "},
{number:58 , escaped: "\'bb", unescaped: "»",name: " Right angle quotes "},
{number:58 , escaped: "\'bc", unescaped: "¼",name: " One-fourth fraction "},
{number:58 , escaped: "\'bd", unescaped: "½",name: " One-half fraction "},
{number:58 , escaped: "\'be", unescaped: "¾",name: " Three-fourths fraction "},
{number:58 , escaped: "\'bf", unescaped: "¿",name: " Inverted question mark "},
{number:58 , escaped: "\'c0", unescaped: "À",name: " A-grave "},
{number:58 , escaped: "\'c1", unescaped: "Á",name: " A-acute "},
{number:58 , escaped: "\'c2", unescaped: "Â",name: " A-circumflex "},
{number:58 , escaped: "\'c3", unescaped: "Ã",name: " A-tilde "},
{number:58 , escaped: "\'c4", unescaped: "Ä",name: " A-diaeresis "},
{number:58 , escaped: "\'c5", unescaped: "Å",name: " A-ring "},
{number:58 , escaped: "\'c6", unescaped: "Æ",name: " AE-ligature "},
{number:58 , escaped: "\'c7", unescaped: "Ç",name: " C-cedilla "},
{number:58 , escaped: "\'c8", unescaped: "È",name: " E-grave "},
{number:58 , escaped: "\'c9", unescaped: "É",name: " E-acute "},
{number:58 , escaped: "\'ca", unescaped: "Ê",name: " E-circumflex "},
{number:58 , escaped: "\'cb", unescaped: "Ë",name: " E-diaeresis "},
{number:58 , escaped: "\'cc", unescaped: "Ì",name: " I-grave "},
{number:58 , escaped: "\'cd", unescaped: "Í",name: " I-acute "},
{number:58 , escaped: "\'ce", unescaped: "Î",name: " I-circumflex "},
{number:58 , escaped: "\'cf", unescaped: "Ï",name: " I-diaeresis "},
{number:58 , escaped: "\'d0", unescaped: "Ð",name: " Uppercase edh "},
{number:58 , escaped: "\'d1", unescaped: "Ñ",name: " N-tilde "},
{number:58 , escaped: "\'d2", unescaped: "Ò",name: " O-grave "},
{number:58 , escaped: "\'d3", unescaped: "Ó",name: " O-acute "},
{number:58 , escaped: "\'d4", unescaped: "Ô",name: " O-circumflex "},
{number:58 , escaped: "\'d5", unescaped: "Õ",name: " O-tilde "},
{number:58 , escaped: "\'d6", unescaped: "Ö",name: " O-diaeresis "},
{number:58 , escaped: "\'d7", unescaped: "×",name: " Multiply sign "},
{number:58 , escaped: "\'d8", unescaped: "Ø",name: " O-slash "},
{number:58 , escaped: "\'d9", unescaped: "Ù",name: " U-grave "},
{number:58 , escaped: "\'da", unescaped: "Ú",name: " U-acute "},
{number:58 , escaped: "\'db", unescaped: "Û",name: " U-circumflex "},
{number:58 , escaped: "\'dc", unescaped: "Ü",name: " U-diaeresis "},
{number:58 , escaped: "\'dd", unescaped: "Ý",name: " Y-acute "},
{number:58 , escaped: "\'de", unescaped: "Þ",name: " Uppercase thorn "},
{number:58 , escaped: "\'df", unescaped: "ß",name: " German ess-zed "},
{number:58 , escaped: "\'e0", unescaped: "à",name: " a-grave "},
{number:58 , escaped: "\'e1", unescaped: "á",name: " a-acute "},
{number:58 , escaped: "\'e2", unescaped: "â",name: " a-circumflex "},
{number:58 , escaped: "\'e3", unescaped: "ã",name: " a-tilde "},
{number:58 , escaped: "\'e4", unescaped: "ä",name: " a-diaeresis "},
{number:58 , escaped: "\'e5", unescaped: "å",name: " a-ring "},
{number:58 , escaped: "\'e6", unescaped: "æ",name: " ae-ligature "},
{number:58 , escaped: "\'e7", unescaped: "ç",name: " c-cedilla "},
{number:58 , escaped: "\'e8", unescaped: "è",name: " e-grave "},
{number:58 , escaped: "\'e9", unescaped: "é",name: " e-acute "},
{number:58 , escaped: "\'ea", unescaped: "ê",name: " e-circumflex "},
{number:58 , escaped: "\'eb", unescaped: "ë",name: " e-diaeresis "},
{number:58 , escaped: "\'ec", unescaped: "ì",name: " i-grave "},
{number:58 , escaped: "\'ed", unescaped: "í",name: " i-acute "},
{number:58 , escaped: "\'ee", unescaped: "î",name: " i-circumflex "},
{number:58 , escaped: "\'ef", unescaped: "ï",name: " i-diaeresis "},
{number:58 , escaped: "\'f0", unescaped: "ð",name: " Lowercase edh "},
{number:58 , escaped: "\'f1", unescaped: "ñ",name: " n-tilde "},
{number:58 , escaped: "\'f2", unescaped: "ò",name: " o-grave "},
{number:58 , escaped: "\'f3", unescaped: "ó",name: " o-acute "},
{number:58 , escaped: "\'f4", unescaped: "ô",name: " o-circumflex "},
{number:58 , escaped: "\'f5", unescaped: "õ",name: " o-tilde "},
{number:58 , escaped: "\'f6", unescaped: "ö",name: " o-diaeresis "},
{number:58 , escaped: "\'f7", unescaped: "÷",name: " Division sign"},
{number:58 , escaped: "\'f8", unescaped: "ø",name: " o-slash "},
{number:58 , escaped: "\'f9", unescaped: "ù",name: " u-grave "},
{number:58 , escaped: "\'fa", unescaped: "ú",name: " u-acute "},
{number:58 , escaped: "\'fb", unescaped: "û",name: " u-circumflex "},
{number:58 , escaped: "\'fc", unescaped: "ü",name: " u-diaeresis "},
{number:58 , escaped: "\'fd", unescaped: "ý",name: " y-acute "},
{number:58 , escaped: "\'fe", unescaped: "þ",name: " Lowercase thorn "},
{number:58 , escaped: "\'ff", unescaped: "ÿ",name: " y-diaeresis "},
];
