

var codePage =
[
//  ["\\}" , "}", "Double quote "],
  //["\\{", "{", " Number "],
//  ["\\'20", " ", " Space"],
  //["\\'21", "!", " Exclamation mark "],
  ["\\'22" , "\"", "Double quote "],
  ["\\'23", "#", " Number "],
  ["\\'24" , "$", "Dollar "],
  ["\\'25", "%", " Percent "],
  ["\\'26", "&", " Ampersand "],
  ["\\'27" , "'", "Apostrophe "],
  ["\\'28", "(", " Left parenthesis "],
  ["\\'29", ")", " Right parenthesis "],
  ["\\'2a" , "*", "Asterisk "],
  ["\\'2b", "+", " Plus sign "],
  ["\\'2c" , ",", "Comma "],
  ["\\'2d", "-", " Hyphen"],
  ["\\'2e" , ".", " , Period" ],
  ["\\'2f" , "/", "Slash" ],
  /*["\\'30" , "0", ""],
  ["\\'31" , "1", ""],
  ["\\'32" , "2", ""],
  ["\\'33" , "3", ""],
  ["\\'34" , "4", ""],
  ["\\'35" , "5", ""],
  ["\\'36" , "6", ""],
  ["\\'37" , "7", ""],
  ["\\'38" , "8", ""],
  ["\\'39" , "9", ""],*/
  ["\\'3a", ":", " Colon "],
  ["\\'3b", ";", " Semicolon "],
  ["\\'3c", "<", " Less-than sign "],
  ["\\'3d", "=", " Equals sign "],
  ["\\'3e", ">", " Greater-than sign "],
  ["\\'3f", "?", " Question mark "],
  ["\\'40", "@", " Commercial at sign "],
  /*["\\'41", "A", ""],
  ["\\'42", "B", " "],
  ["\\'43", "C", " "],
  ["\\'44", "D", " "],
  ["\\'45", "E", " "],
  ["\\'46", "F", " "],
  ["\\'47", "G", " "],
  ["\\'48", "H", " "],
  ["\\'49", "I", " "],
  ["\\'4a", "J", " "],
  ["\\'4b", "K", " "],
  ["\\'4c", "L", " "],
  ["\\'4d", "M", " "],
  ["\\'4e", "N", " "],
  ["\\'4f", "O", " "],
  ["\\'50", "P", " "],
  ["\\'51", "Q", " "],
  ["\\'52", "R", " "],
  ["\\'53", "S", " "],
  ["\\'54", "T", " "],
  ["\\'55", "U", " "],
  ["\\'56", "V", " "],
  ["\\'57", "W", " "],
  ["\\'58", "X", " "],
  ["\\'59", "Y", " "],
  ["\\'5a", "Z", " "],*/
  ["\\'5b", "[", " Left square bracket 92 , \'5c , \ , Backslash "],
  ["\\'5d", "]", " Right square bracket "],
  ["\\'5e", "^", " Caret "],
  ["\\'5f", "_", " Underscore "],
  ["\\'60", "`", " Grave accent "],
/*  ["\\'61", "a", " "],
  ["\\'62", "b", " "],
  ["\\'63", "c", " "],
  ["\\'64", "d", " "],
  ["\\'65", "e", " "],
  ["\\'66", "f", " "],
  ["\\'67", "g", " "],
  ["\\'68", "h", " "],
  ["\\'69", "i", " "],
  ["\\'6a", "j", " "],
  ["\\'6b", "k", " "],
  ["\\'6c", "l", " "],
  ["\\'6d", "m", " "],
  ["\\'6e", "n", " "],
  ["\\'6f", "o", " "],
  ["\\'70", "p", " "],
  ["\\'71", "q", " "],
  ["\\'72", "r", " "],
  ["\\'73", "s", " "],
  ["\\'74", "t", " "],
  ["\\'75", "u", " "],
  ["\\'76", "v", " "],
  ["\\'77", "w", " "],
  ["\\'78", "x", " "],
  ["\\'79", "y", " "],
  ["\\'7a", "z", " "],*/
  ["\\'7c", "|", " Vertical bar "],
  ["\\'7d", "]", " Right curly brace "],
  ["\\'7e", "~", " Tilde "],
  ["\\'80", "€", ""],
  ["\\'83", "ƒ", " Florin "],
  ["\\'84", "",", , Low left double quote "],
  ["\\'85", "...", " Ellipsis "],
  ["\\'86", "†", " Dagger "],
  ["\\'87", "‡", " Double dagger "],
  ["\\'88", "∘", " Circumflex "],
  ["\\'89", "‰", " Permil "],
  ["\\'8a", "Š", " S-caron "],
  ["\\'8b", "‹", " Single left guillemet "],
  ["\\'8c", "Œ", " OE-ligature "],
  ["\\'8e", "Ž", " Z-caron "],
  ["\\'91", "‘", " Left single quote "],
  ["\\'92", "’", " Right single quote "],
  ["\\'93", "“", " Left double quote "],
  ["\\'94", "”", " Right double quote "],
  ["\\'95", "•", " Bullet "],
  ["\\'96", "–", " En dash "],
  ["\\'97", "—", " Em dash "],
  ["\\'98", "~", " Tilde "],
  ["\\'99", "™", " Trademark "],
  ["\\'9a", "š", " s-caron "],
  ["\\'9b", "›", " Single right guillemet "],
  ["\\'9c", "œ", " oe ligature "],
  ["\\'9e", "ž", " z-caron "],
  ["\\'9f", "Ÿ", " Y-diaeresis "],
  //["\\~", " ", " Nonbreaking space"],
  ["\\'a1", "¡", " Inverted exclamation point "],
  ["\\'a2", "¢", " Cent sign "],
  ["\\'a3", "£", " Pound sign "],
  ["\\'a4", "¤", " General currency sign "],
  ["\\'a5", "¥", " Yen sign "],
  ["\\'a6", "¦", " Broken vertical bar "],
  ["\\'a7", "§", " Section sign "],
  ["\\'a8", "¨", " Spacing diaeresis "],
  ["\\'a9", "©", " Copyright "],
  ["\\'aa", "ª", " Feminine ordinal "],
  ["\\'ab", "«", " Left angle quotes "],
  ["\\'ac", "¬", " Not sign "],
  ["\\-", "-", " Soft hyphen"],
  ["\\'ae", "®", " Registered trademark"],
  ["\\'af", "¯", " Macron accent "],
  ["\\'b0", "°", " Degree sign "],
  ["\\'b1", "±", " Plus or minus sign "],
  ["\\'b2", "²", " Superscript 2 "],
  ["\\'b3", "³", " Superscript 3 "],
  ["\\'b4", "´", " Acute accent "],
  ["\\'b5", "µ", " Micro sign (Greek mu) "],
  ["\\'b6", "¶", " Paragraph sign "],
  ["\\'b7", "·", " Middle dot "],
  ["\\'b8", "¸", " Cedilla "],
  ["\\'b9", "¹", " Superscript 1 "],
  ["\\'ba", "º", " Masculine ordinal "],
  ["\\'bb", "»", " Right angle quotes "],
  ["\\'bc", "¼", " One-fourth fraction "],
  ["\\'bd", "½", " One-half fraction "],
  ["\\'be", "¾", " Three-fourths fraction "],
  ["\\'bf", "¿", " Inverted question mark "],
  ["\\'c0", "À", " A-grave "],
  ["\\'c1", "Á", " A-acute "],
  ["\\'c2", "Â", " A-circumflex "],
  ["\\'c3", "Ã", " A-tilde "],
  ["\\'c4", "Ä", " A-diaeresis "],
  ["\\'c5", "Å", " A-ring "],
  ["\\'c6", "Æ", " AE-ligature "],
  ["\\'c7", "Ç", " C-cedilla "],
  ["\\'c8", "È", " E-grave "],
  ["\\'c9", "É", " E-acute "],
  ["\\'ca", "Ê", " E-circumflex "],
  ["\\'cb", "Ë", " E-diaeresis "],
  ["\\'cc", "Ì", " I-grave "],
  ["\\'cd", "Í", " I-acute "],
  ["\\'ce", "Î", " I-circumflex "],
  ["\\'cf", "Ï", " I-diaeresis "],
  ["\\'d0", "Ð", " Uppercase edh "],
  ["\\'d1", "Ñ", " N-tilde "],
  ["\\'d2", "Ò", " O-grave "],
  ["\\'d3", "Ó", " O-acute "],
  ["\\'d4", "Ô", " O-circumflex "],
  ["\\'d5", "Õ", " O-tilde "],
  ["\\'d6", "Ö", " O-diaeresis "],
  ["\\'d7", "×", " Multiply sign "],
  ["\\'d8", "Ø", " O-slash "],
  ["\\'d9", "Ù", " U-grave "],
  ["\\'da", "Ú", " U-acute "],
  ["\\'db", "Û", " U-circumflex "],
  ["\\'dc", "Ü", " U-diaeresis "],
  ["\\'dd", "Ý", " Y-acute "],
  ["\\'de", "Þ", " Uppercase thorn "],
  ["\\'df", "ß", " German ess-zed "],
  ["\\'e0", "à", " a-grave "],
  ["\\'e1", "á", " a-acute "],
  ["\\'e2", "â", " a-circumflex "],
  ["\\'e3", "ã", " a-tilde "],
  ["\\'e4", "ä", " a-diaeresis "],
  ["\\'e5", "å", " a-ring "],
  ["\\'e6", "æ", " ae-ligature "],
  ["\\'e7", "ç", " c-cedilla "],
  ["\\'e8", "è", " e-grave "],
  ["\\'e9", "é", " e-acute "],
  ["\\'ea", "ê", " e-circumflex "],
  ["\\'eb", "ë", " e-diaeresis "],
  ["\\'ec", "ì", " i-grave "],
  ["\\'ed", "í", " i-acute "],
  ["\\'ee", "î", " i-circumflex "],
  ["\\'ef", "ï", " i-diaeresis "],
  ["\\'f0", "ð", " Lowercase edh "],
  ["\\'f1", "ñ", " n-tilde "],
  ["\\'f2", "ò", " o-grave "],
  ["\\'f3", "ó", " o-acute "],
  ["\\'f4", "ô", " o-circumflex "],
  ["\\'f5", "õ", " o-tilde "],
  ["\\'f6", "ö", " o-diaeresis "],
  ["\\'f7", "÷", " Division sign"],
  ["\\'f8", "ø", " o-slash "],
  ["\\'f9", "ù", " u-grave "],
  ["\\'fa", "ú", " u-acute "],
  ["\\'fb", "û", " u-circumflex "],
  ["\\'fc", "ü", " u-diaeresis "],
  ["\\'fd", "ý", " y-acute "],
  ["\\'fe", "þ", " Lowercase thorn "],
  ["\\'ff", "ÿ", " y-diaeresis "],
];
/*
for(var k in codePage){
  console.log(codePage[k][1]);
}
*/
//throw new Error("Something went badly wrong!");
